name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '00 01 * * *'

permissions:
  contents: read

jobs:
  test:
    name: test
    env:
      CARGO: cargo
      TARGET_FLAGS: 
      TARGET_DIR: ./target
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: stable-linux
          os: ubuntu-latest
          rust: stable
        - build: beta-linux
          os: ubuntu-latest
          rust: beta
        - build: nightly-linux
          os: ubuntu-latest
          rust: nightly
        - build: stable-macos
          os: macos-latest
          rust: stable
        - build: stable-windows
          os: windows-latest
          rust: stable
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Build asp-classic-parser
      run: ${{ env.CARGO }} build --verbose ${{ env.TARGET_FLAGS }}

    - name: Run tests
      run: ${{ env.CARGO }} test --verbose ${{ env.TARGET_FLAGS }}

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - name: Run clippy
      run: cargo clippy -- -D warnings

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --workspace